### ISSUE TITLE
when I excute this code(charSeqRNN.py),I got the problem

### ISSUE THREAD

**Issue by WYCAS** [fwillett/handwritingBCI#2]
File "D:/SIAT/DATA/handwritingBCI-main/charSeqRNN.py", line 826, in cudnnGraphSingleLayer
    rnn_cudnn.build(inputSize)
  File "D:\Software\Anaconda\envs\py36\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 529, in build
    self.input_spec[0] = get_input_spec(input_shape)
  File "D:\Software\Anaconda\envs\py36\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py", line 508, in get_input_spec
    input_spec_shape[time_step_index] = None
IndexError: list assignment index out of range

when I excute this code(charSeqRNN.py),I got the bug.how can I sovle this problem,thx !!!

**Comment by fwillett** [comment]
We haven't seen that one before - my guess would be that the version of tensorflow you are using is different from v1.15 GPU? https://www.tensorflow.org/install/pip. Not sure what else would cause it. Also, did you modify that file? Looks like the original version has rnn_cudnn.build at line 800.

**Comment by WYCAS** [comment]
thanks a lot ! I was using the wrong CUDA

**Comment by fwillett** [comment]
Great, glad it's working now!

**Comment by ajay-sreeram** [comment]
@WYCAS can you tell, whats the correct CUDA is

Thank you

**Comment by ajay-sreeram** [comment]
When I try in Kaggle, I am getting this error `Fail to find the dnn implementation.` 
https://www.kaggle.com/ajaysreeram/inference-test-gpu/

@fwillett can you please help me in finding if this is because of wrong cuda or something else.

(Here I am trying to synthetically generate a neural input for a given sentence and trying to get same sentence as output)

**Comment by ajay-sreeram** [comment]
It is working on using tensorflow 1.14, which is provided as default in that notebook kernel. 

Thankyou
