### ISSUE TITLE
Questions about the reference electrode position and timewarp figures

### ISSUE THREAD

**Issue by Wasabi111** [fwillett/handwritingBCI#3]
Hi Francis,

I have two questions about some details in your paper High-performance brain-to-text communication via handwriting and I would appreciate it if you could help me.

The first question is about the reference electrode position. I checked the paper as well as the supplement materials but could not find the information about reference electrode. I wonder if the device has a reference electrode and if so, where it should be placed.

The second question is about the first step "time-warping" and it contains two parts. On Github, the aligned figure of trials of each single letter looks like a spike. My first part of question is about the x-axis of the figure. Does it mean 200 time bin and each bin is 10ms? If so, here comes my second part of question, is the 2-second trial signal real neural spiking or just the first compoent of PCA, but just looks like a spiking signal. According to my knowledge, the neural spiking signal should be much shorter than 2 seconds, 2 ms maybe.

Thank you very much! I am looking forward for your reply!

Best regards,

Dongming

**Comment by fwillett** [comment]
Hi Dongming,

Thanks for your interest in the work!

(1) Special reference wires are used for the reference, not a particular electrode. See for example figure 1 of this document which shows the reference wires for the Utah array: https://blackrockneurotech.com/research/wp-content/ifu/Utah_Array_Surgical_Manual_Research.pdf

(2) In the example figure, 200 time bins are plotted, with each bin lasting 10 ms (therefore you are correct that the whole figure shows 2 seconds of data). The fact that it looks like a neural spike is just a coincidence - it doesn't correspond to a single neural spike, rather an increase/decrease in firing rate across the neural population. 

Best,
Frank

**Comment by Wasabi111** [comment]
Thank you very much, Frank!
