### ISSUE TITLE
what is the GPU memory size used in your experiment？

### ISSUE THREAD

**Issue by xy21yue** [fwillett/handwritingBCI#6]
what is the GPU memory size used in your experiment？
now， I am trying to train the RNN model with your GitHub code on GPU 16G， but I encounter an error “Fail to find the dnn implementation.”  Then I operate the same experiment with the GPU 24G platform but a similar error appeared: 
"(0) Internal: Blas xGEMMBatched launch failed : a.shape=[2,7500,192], b.shape=[2,192,192], m=7500, n=192, k=192, batch_size=2[[{{node MatMul}}]] [[GatherV2/_43]] "

**Comment by fwillett** [comment]
Shouldn't be a memory issue, I used a GeForce GTX 1080 Ti, which only has 11 GB. Probably a tensorflow version / CUDA / cuDNN issue.
