### ISSUE TITLE
Could you share how to check the effect of single-character classification?

### ISSUE THREAD

**Issue by 0012xuqian** [fwillett/handwritingBCI#7]
Dear Dr. Fwillett,

I would like to express my gratitude for sharing your code. I have some problems trying to reproduce character classification and use T-SNE to see the classification effect. I have noticed that the scatter plot generated in my replication appears to have more concentrated clusters compared to the perfect separation achieved in the image presented in your paper. Although classification can also be achieved, no matter how I debug it, it is not as remarkable as the effect in your paper.

I would greatly appreciate it if you could provide me with some insights or details regarding the character classification process that could help me improve the visualization results. Thank you very much in advance for your assistance.

Best regards,
XuQian

**Comment by fwillett** [comment]
Hi XuQian! I uploaded a new script "tsneAndKNNExample.m" in the "matlabExamples" folder that shows how to do classification and t-SNE exactly as it was done in the paper. Hope this helps!
